trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

variables:
  environmentUrl: 'https://pdgeek.crm.dynamics.com'
  clientId: '7d492969-4929-4440-a7a9-2a46a377e464'
  clientSecret: $(CLIENT_SECRET)
  tenantId: '935b06c0-ed5f-4d24-aeb8-517e8372d700'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet tool install --global Microsoft.PowerApps.CLI.Tool
  displayName: 'Install Power Platform CLI'

- script: |
    pac auth create --url $(environmentUrl) --clientId $(clientId) --clientSecret $(clientSecret) --tenantId $(tenantId)
    pac solution import --path ./definition.json --overwrite --publish-changes
  displayName: 'Authenticate and Import Power Platform Solution'
